name: HYBRID_APP
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.2
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^17.2.2
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  device_info_plus: ^10.1.2
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  logger: ^2.4.0
  kakao_flutter_sdk: ^1.8.0
  uni_links: ^0.5.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  flutter_naver_login_plus: ^1.0.2
  android_id: ^0.4.0
  go_router: ^14.6.3
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - dev.env
    - prod.env
    - assets/jpg/
    - assets/png/