name: HYBRID_APP
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  fluttertoast: ^9.0.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.0.3
  firebase_core: ^4.2.0
  device_info_plus: ^12.2.0
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.7
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  logger: ^2.5.0
  kakao_flutter_sdk: ^1.9.7+3
  app_links: ^6.4.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  android_id: ^0.4.0
  go_router: ^16.3.0
  flutter_riverpod: ^3.0.3
  app_badge_plus: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - dev.env
    - prod.env
    - assets/jpg/
    - assets/png/