-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgEEsozSXCH0DylUzn
2WQ9NSfHRlRP6nd35gdnRmtwyImgCgYIKoZIzj0DAQehRANCAATBOyHj9I6XPUvj
KNK5U3VfbUPwa+C/WHeGc7kZ92wmMLLtdzxCzzaQIGJCmL5UO7kOt/+Y0JbWB5Ln
6lBIhhST
-----END PRIVATE KEY-----